### ISSUE TITLE
Something's gone wrong [Gnome 42.1]

### ISSUE THREAD

**Issue by samiurprapon** [alejandro-mouras/rog-manager#10]
Failed to install the extension. 

Here's the log - 

```
TypeError: widget.show_all is not a function

Stack trace:
  buildPrefsWidget@/home/saminux/.local/share/gnome-shell/extensions/rog-manager@rog/prefs.js:81:10
  _init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:32:44
  ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:129:33
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by sakshamprakash01** [comment]
same issue, has anyone been able to find a solution to this?

**Comment by samiurprapon** [comment]
> same issue, has anyone been able to find a solution to this?

Instead try this - [asusctl](https://gitlab.com/asus-linux/asusctl) . This just works fine on  **Gnome 42.3.1**
